### ISSUE TITLE
How to cancel a download?

### ISSUE THREAD

**Issue by bordoloicorp** [ibrod83/nodejs-file-downloader#10]
Hi, I was able to start a download very easily following the read-me! But now I want to cancel a download. 
I didn't find a way to cancel a download. Any help is greatly appreciated! Thanks in advance!

**Comment by ibrod83** [comment]
Currently, the only "straight forward" way to cancel a download, is after the response was received, but BEFORE the readable stream(IncomingMessage) is piped into the writable stream("saving the file"). If this suits your needs, reffer to the "Hook into response" documentation.

I will think what is the best way to add a cancelation feature to an active download, given the nature of my promise-based  API. thank you for pointing out the need for this feature.

**Comment by bordoloicorp** [comment]
Thank you for taking it as feature request. It will be really helpful to stop a download after the download started.

**Comment by ibrod83** [comment]
Can you give me the exact scenario you're facing, so that it would easier for me to understand the various situations a user might encounter?

**Comment by bordoloicorp** [comment]
Okay. 
Basically I am building an electron app where I am using your package to download some stuff. 
I have a button to start the download and another button to cancel the download. 
I was able to start the download easily but now stuck at cancellation.
I am now looking at  [electron-dl](https://www.npmjs.com/package/electron-dl) package but it has some other limitations.

**Comment by ibrod83** [comment]
Ah, this is actually very interesting. I was thinking about it after you opened the issue, and asked my self, "what could be the usage of such a feature, in UI-less application". But, as you said,  your application has a UI. Try checking out a package called "node-downloader-helper", it has cancelation abilities

**Comment by bordoloicorp** [comment]
Thanks so much!! Should I close the issue?
