### ISSUE TITLE
How to add headers?

### ISSUE THREAD

**Issue by QC-Development** [ibrod83/nodejs-file-downloader#12]
How can I add for headers? like user agent and Referer. If without it, it will be 403 error occur.

**Comment by ibrod83** [comment]
In your config object, jsut add a field headers:{...}
```
const downloader = new Downloader({
    url:"some url",
    directory:"./",
    headers:{
      'some-header':"some-value"
    }
  })

```
Tell me if it worked for you, i don't have this covered in the tests...

**Comment by QC-Development** [comment]
It works well. Epic.
