### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by kije** [ibrod83/nodejs-file-downloader#13]
Hi, and thanks for this great library.

Please consider adding a changelog to the repository, or use gihub releases with release notes, so upgrading to never versions of the library gets easier/less risky for user's of the library.

E.g. I currently use v4.4.2 of the library and want to upgrade to the latest version (v4.5.1), but I currently have no information (other than investigating the commit history) of what's changed or what got fixed.

**Comment by ibrod83** [comment]
ah yes....you are right. Notice that i follow the semver convention, so there shouldn't be any breaking changes between 4.4.2 and 4.5.1. I thoroughly test it automatically and manually, though of course there's never 100%.
