### ISSUE TITLE
downloading several files at once does not work (at the end, all are lost)

### ISSUE THREAD

**Issue by kravetsone** [ibrod83/nodejs-file-downloader#18]
downloading several files at once does not work (at the end, all are lost)

**Comment by ibrod83** [comment]
Can you give some code example? Also, what node version and what OS?

**Comment by kravetsone** [comment]
config.episodes.map(x => {
    const downloader = new Downloader({
      url: x.link,
      directory: `${path}/${anime.title}`,
      fileName: `${x.name}.mp4`,
      maxAttempts: 10,
      skipExistingFileName: true,
      onProgress:function(percentage,chunk,remainingSize){
            x.bar.update(x.fileSize-remainingSize);
       },
       onResponse:function(response) {
           x.fileSize = Number(response.headers['content-length']);
           x.bar = multibar.create(x.fileSize, 0, {
    file: x.name+".mp4"
           });
       }
    })
  downloader.download().then(function () {
    console.log(`Серия ${x.name} успешно скачана`);
  })
  .catch(function (error) {
    console.log(x.name, error);
  });
    });
OS: windows 10, node js version: 16.0.0

after at least one element finishes loading, all the others will start it
from the beginning for some unknown reason

пт, 16 июл. 2021 г., 13:16 ibrod83 ***@***.***>:

**Comment by ibrod83** [comment]
My guess is that it has something to do with the fact you're shooting a very large number of requests at once. Are you getting any error? How many items does config.episodes contain? 

Also, i see you're using different directories, dpeending on anime.title. If those directories do not exist, and some of these files have the same title- it's possible the error comes from multiple attempts to create the same folder...

**Comment by kravetsone** [comment]
There are 13 elements in "config.episodes", errors do not come, the event
is simply reused in the function (onResponse)
The folder is created before the code that I threw off) so there is a
folder in any case
The file names are always different

сб, 17 июл. 2021 г., 23:42 ibrod83 ***@***.***>:

**Comment by ibrod83** [comment]
What do you mean by "the event is simply reused in the function (onResponse)"? Can you try without onResponse, and see if it works?

**Comment by fearrr** [comment]
I have the same behavior. Can u place an example of how to download multiple files at once???

**Comment by ibrod83** [comment]
I will. Can you in the meanwhile paste your own code?

**Comment by fearrr** [comment]
> I will. Can you in the meanwhile paste your own code?

I already got it to work correctly.
It will be cool if you still (as the author of this package) place the best practice of using multiple downloads

```
downloads.map(d => {
    const downloader = new Downloader({
      url: d.url,
      directory: `${path}`,
      fileName: `${d.name}.mp4`,
      maxAttempts: 3,
      skipExistingFileName: true,
      onProgress: function (percentage, chunk, remainingSize) {
	      console.log(`${d.name} — ${percentage} %`);
    	},
    })
  downloader.download().then(function () {
    console.log(`${d.name} Download Done!`);
  })
  .catch(function (error) {
    console.log(d.name, error);
  });
});
```

**Comment by ibrod83** [comment]
So, I can tell you immediately that using map is problematic, because you are executing all requests IN PARALLEL. If your array contains 1000 items, this means 1000 requests will be initiated almost at once. Behind the scenes, the program checks if the directory exists(in an async way) and if the file exists, which might lead to some collisions. 

I would use a for of loop, and shoot each request sequentially, or at least use some task queue to limit the concurrent operations.
