### ISSUE TITLE
Set maximum file size

### ISSUE THREAD

**Issue by MichaelMikeJones** [ibrod83/nodejs-file-downloader#2]
I'm trying to make an upload by URL endpoint, and your package works great to download the files, but I wanted to implement a maximum file size, so large files won't be downloaded. Is it possible in your package?

**Comment by ibrod83** [comment]
No, there is no such feature. But i'm not sure i understand your problem.

**Comment by MichaelMikeJones** [comment]
Like in my case if the user sent a link of a file let's say bigger than 2GB, I want to send back an error indicating the file size limitation of 2GB, so storage won't get full quickly.
I'm using the latest version, thanks for the warning.

**Comment by ibrod83** [comment]
Can you maybe show me some code..? you have a public repository? seems you have some uploading functionality, which is unrelated to the package

**Comment by MichaelMikeJones** [comment]
This is my code:
```
exports.uploadFileByUrl = CatchAsync(async(req, res, next) => {
    const url = req.body.url;
    const [filename, ext] = path.basename(url).split(".");
    const downloader = new Downloader({
        url,
        directory: "public/content",
        fileName: `${filename}-${req.user._id}-${Date.now()}.${ext}`,
    });

    await downloader.download();

    // creating req.file
    req.file = {};
    req.file.size = downloader.fileSize;
    req.file.mimetype = downloader.response.headers["content-type"];
    req.file.filename = downloader.config.fileName;
    req.file.path = `content/${downloader.config.fileName}`;

    next();
});
```
I have an upload functionality, it works in this way: 
1 - user provides a link of a file (not the actual file)
2 - Node backend (which is my server) get the link and downloads the file using your package
3 - then backend sends back a response containing the result and the actual path to the file in my own server

And there is no problem with your package. I only want to set a limitation on the size of the file that is gonna be downloaded.
Is it possible with your package? I wanted something like this
```
const downloader = new Downloader({
        url,
        directory: "public/content",
        fileName: `${filename}-${req.user._id}-${Date.now()}.${ext}`,
        maxFileSize: 2000000000 // like in bytes
    });
```
cause I thought there might be a feature like this and it would be straight forward.

**Comment by ibrod83** [comment]
Nah sorry, there is no such feature.

**Comment by ibrod83** [comment]
I'll add this feature in the upcoming days..might be useful for others maybe too.

**Comment by MichaelMikeJones** [comment]
I was thinking, it actually doesn't make much sense to set a property like `maxFileSize` for a download functionality. Instead I thought maybe it would be better, if you could implement a functionality to perform a HEAD request of the given url when a new instance of `downloader` is created.
Then, before `await downloader.download()` we can check for headers which includes `content-length` and much more.

For example in my case I can check for ```
if (dl.headers['content-length'] > limit) {
     // send back error
}
```
I think this way it would give developers more control.

**Comment by ibrod83** [comment]
This is a good idea, but it undermines the current API of the program. notice that the instance of Downloader doesn't really do anything, whereas Downloader.download() performs two actions: it makes the https request, and streams the response to the harddrive.

I guess i should've built it a bit more modular, maybe ill do it in the future.

I suggest that if you really need such customization, maybe you shouldn't be using this package, because it serves the purpose of completely simplifying the download process, and nothing else.

Maybe it would be better for you to "manually" download the files using Axios(very easy), or even use Node's http module directly(understanding how streams work is very useful, and it's much simpler than people think).

Also i noticed that in your code, duplicate file names are impossible, so one of the key features of my package is irrelevant for you(it takes care automatically of such scenarios).

**Comment by ibrod83** [comment]
Another important think: I noticed that you do not have any error handling in your code. If, for some reason, the await download() fails, Your entire code will fail and maybe even the Node process will crash. 

I recommend that you put the download() function inside try-catch block, and take care of a possible failure. Also, it would be good if the program would automatically repeat this procedure. Take a look at some other package of mine:  https://www.npmjs.com/package/repeat-promise-until-resolved
This allows you to repeat any promise-based operation, until it actually succeeds. Very useful for many scenarios, also in the browser.

**Comment by ibrod83** [comment]
In case this is still relevant: i've uploaded a new version. Now you can get the response object, and decide if you want to download the file. There is an example dealing with your case.
