### ISSUE TITLE
Can't reach response on error

### ISSUE THREAD

**Issue by beryasar** [ibrod83/nodejs-file-downloader#24]
When the request returns 400, I can't reach the detailed message of the error coming from the API? Is it possible for me to access this message somehow?

**Comment by ibrod83** [comment]
Can you give me a code example? Because in my tests, I clearly see the error object in case of 400.

**Comment by beryasar** [comment]
await (async () => {
    const downloader = new Downloader({
      url: url,
      directory: "./"
    });
    try {
      await downloader.download();
      console.log("All done");
    } catch (error) {
      console.log("Download failed-->", error);
    }
  })();

**Comment by beryasar** [comment]
Here is my code:

// url coming another function
await (async () => {
    const downloader = new Downloader({
      url: url,
      directory: "./"
    });
    try {
      await downloader.download();
      console.log("All done");
    } catch (error) {
      console.log("Download failed", error);
    }
  })();

In this code sample, when status is 400, I get a try catch as expected, but I also want to reach the response body in this try catch because I want to reach the error message.

**Comment by ibrod83** [comment]
When i throw the error object, i do not make a reference to the request object. You're probably used to having it from Axios, It's actually a good idea to implement this. Currently i don't see any way to access the request object. But why do you actually need it?

**Comment by beryasar** [comment]
I need this because they have put multiple error messages for 400 error code in the API I am using.

**Comment by ibrod83** [comment]
I've added a reference to node's response object, to the Error. Manual handling is still needed
