### ISSUE TITLE
Send the response body in the error

### ISSUE THREAD

**Issue by IonicaBizau** [ibrod83/nodejs-file-downloader#29]
First of all, thank you for the amazing module!  ⭐ 

It would be great to get the response body in case of error and send it in the error handler.

**Usecase**
Using the GitHub API to download the tarball, if the response is invalid, we can only know that it failed (e.g. 403), but the response body would contain the reason why it failed.

**Comment by ibrod83** [comment]
You mean this?
https://github.com/ibrod83/nodejs-file-downloader#getting-the-response-object-during-an-error

Note that it's not very friendly, it just exposes the stream object, but if you follow the example you can get what you need. I plan to make it more axios-like in the future

**Comment by IonicaBizau** [comment]
Exactly! That would make it more convenient if it were part of the library
codebase.

**Comment by ibrod83** [comment]
I've added a reference to the response body. Now it should work as u expect. Note that the property you need to access is error.responseBody. If you have an existing code streaming error.response, it will fail to work as expected. Upgrade to latest version and tell me how it went :D

**Comment by IonicaBizau** [comment]
Thank you! That is so cool and will be helpful for debugging. :) happy new year and keep up the great work!
