### ISSUE TITLE
Resume File Download

### ISSUE THREAD

**Issue by cicerothoma** [ibrod83/nodejs-file-downloader#3]
Is there a way to resume download progress without starting all over. Let's say I'm downloading a really huge file and there's a network issue. Can I resume the file download without starting all over?

**Comment by ibrod83** [comment]
No, there isn't. But what i can recommend you, is to use this package:  https://github.com/ibrod83/repeat-promise-until-resolved

This will allow you to wrap the Downloader.download(), and repeat it automatically in case of an error.

If you really need to be able to resume big downloads, you would need to use Node's http module directly, and manually manage each data package coming from the stream(perhaps there are some npm modules that take care of that)

**Comment by cicerothoma** [comment]
Thank you. @ibrod83. This package is a life-saver. I'm writing a script to download files from the internet and because of this I don't have to do much work. Can I follow you on Twitter?

**Comment by ibrod83** [comment]
i dont have twitter :D Which package did you mean? this one, or repeat-promise-until-resolved?

**Comment by cicerothoma** [comment]
You're not on any social media network? I would really love to connect with you so I can learn more. I'm talking about this package.

**Comment by ibrod83** [comment]
Nah i dont use social media :D
