### ISSUE TITLE
Get downloaded filepath

### ISSUE THREAD

**Issue by j-d-carmichael** [ibrod83/nodejs-file-downloader#36]
Would be great if the response from the promise was an object with the downloaded to filepath

https://github.com/ibrod83/nodejs-file-downloader/blob/master/Downloader.td.ts#L30

**Comment by DudoMan** [comment]
I support

**Comment by cdking007** [comment]
it will great if it return the downloaded file object

**Comment by ibrod83** [comment]
was added in version 4.10.0.
`const {filePath} = await downloader.download()`
