### ISSUE TITLE
Progress of a download return '% NaN'

### ISSUE THREAD

**Issue by d0v3riz** [ibrod83/nodejs-file-downloader#4]
Hello, i dont know why i got value '% NaN'. Maybe bug or i wrong wrote this code ?. Here my code :

```
const Downloader = require('nodejs-file-downloader');

(async () => {

  const downloader = new Downloader({     
    url: 'https://github.com/mongodb/mongo/archive/master.zip',
    directory: "./public/downloads",
    onProgress:function(percentage){
        console.log('% ',percentage)   
    }              
  })
  
  await downloader.download();

  console.log('All done');

})(); 
```

Results :

%  NaN
%  NaN
%  NaN
All done

**Comment by ibrod83** [comment]
Ok i see the problem. My code relies on the existence of a header called "content-length", which isn't received from the URL you're downloading from . I missed that scenario :D. I will check later today if there's some "fallback" way to predict the size of the file, and update the code.
