### ISSUE TITLE
Progress is not 100% even though the file is already downloaded 

### ISSUE THREAD

**Issue by Lott-Noob** [ibrod83/nodejs-file-downloader#43]
I was implementing this package to my discord bot that downloads file on my server. But when I am trying to show the file download progress on discord embed.  using the onProgress percentage. Though the file gets downloaded to my server but the progress still showing its downloading at very slow speed and then the bot gets timeout 

My Code: 

`run: async (client, interaction) => {
        await interaction.deferReply();

        // await interaction.reply({ content: interaction.options.get('link').value })

        const downloader = new Downloader({
            url: interaction.options.get('link').value, 
            directory: "././downloads"
            onProgress(percentage, chunk, remaningSize) {

                const fileDownloadingEmbed = new EmbedBuilder()
                    .setColor(0xffdd1c)
                    .setTitle('File Downloading')
                    .setDescription(percentage+'%')
                    .addFields(
                        { name: 'Filename: ', value: deduceFileNameFromUrl(interaction.options.get('link').value)  },
                        //
                        // { name: 'Download Info', value: 'Total Size: ' + byteHelper(stats.total)+'\n'+'Downloaded: ' + byteHelper(stats.downloaded)+'\n'+ 'Speed: '+ byteHelper(stats.speed)+'s'+'\n' + 'Progress: '+ Math.round(stats.progress)+'%'}
                    ).setFooter({text: 'Upload requested by '+ interaction.user.username , iconURL: interaction.user.displayAvatarURL({size:1024}) } );

                interaction.editReply({embeds: [fileDownloadingEmbed]})
            }

        });

        try {
            await downloader.download();
        } catch (error) {
            console.log(error);
        }
    }
};
`

![image](https://user-images.githubusercontent.com/87697077/187856218-90f459b3-ecfe-45fb-a610-3eeb227d03e8.png)
![image](https://user-images.githubusercontent.com/87697077/187856396-7ccd1025-5cc4-4ad4-b6c5-eea9e2c67e34.png)

**Comment by ibrod83** [comment]
Can you post a simplified code that reproduces the problem? There's too many details and unfamiliar code in your example. I do not know what interaction.deferReply() or EmbedBuilder are.

**Comment by Lott-Noob** [comment]
> Can you post a simplified code that reproduces the problem? There's too many details and unfamiliar code in your example. I do not know what interaction.deferReply() or EmbedBuilder are.

Actually I am using the discord node js api wrapper. And I am showing the progress of downloaded file through a discord bot.😀

**Comment by ibrod83** [comment]
Unfortunately I do not have a way to reproduce this, being that the code is being used in the context of Discord API, which i'm not familiar with.
