### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by OndroNR** [ibrod83/nodejs-file-downloader#5]
We could use follow redirects feature. It could be easily done by replacing http(s) with this equivalent module https://github.com/follow-redirects/follow-redirects . Or at least making this replacement passable.

**Comment by ibrod83** [comment]
Yes, will do.

**Comment by OndroNR** [comment]
This .end() https://github.com/ibrod83/nodejs-file-downloader/blob/087fde6b1d886dae1634a4e667b66a4b04b965c8/request.js#L52 must be moved after request.setTimeout. Then it works well with follow-redirects.

**Comment by ibrod83** [comment]
Done. please notify me if you encounter any problems.

**Comment by OndroNR** [comment]
Thank you!
