### ISSUE TITLE
Downloading from data uri

### ISSUE THREAD

**Issue by EverlyScott** [ibrod83/nodejs-file-downloader#52]
Hello, I'm currently downloading content from an electron app and it downloads data from http sources, as well as data URIs. Is it possible to download via data URIs so I don't have to make a custom system to download those? When I try entering a data URI in the url property, I get the following error:

```
UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: protocol mismatch
```

**Comment by ibrod83** [comment]
Can you paste the code?

**Comment by ibrod83** [comment]
You're right, the program doesn't support data URI. I will try adding support in the nearby future.

**Comment by ibrod83** [comment]
Updated the program to support Data URI. Please tell me if you encounter any problems
