### ISSUE TITLE
About skipExistingFileName and onBeforeSave

### ISSUE THREAD

**Issue by YuJian920** [ibrod83/nodejs-file-downloader#56]
I want to set a custom file name for the downloaded file and append its corresponding file extension. So I used onBeforeSave, but I found that the skipExistingFileName feature stopped working after using onBeforeSave. I can't skip existing files anymore. Is there a way to solve this?

```js
let downloadHelper = new download({
  url,
  skipExistingFileName: true,
  onBeforeSave: (deducedName) => {
    const fileExt = extname(deducedName);
    if (fileExt) return `${item.id}-${item.desc}${fileExt}`;
    return deducedName;
  },
});
```

**Comment by ibrod83** [comment]
i'll check the flow and let you know

**Comment by ibrod83** [comment]
Currently there doesn't seem to be any way around it. There are too many options/hooks around the issue of the file name(a mistake, in retrospective). I might simplify this in the future

**Comment by ibrod83** [comment]
Looking again at the code and after writing a test for this case, it seems that skipExistingFileName actually does work, being that the skipping conditional is invoked BEFORE onBeforeSave. Maybe in your case the problem is that you expect the skipping to be based on the filename you returned from onBeforeSave.

**Comment by YuJian920** [comment]
😭Yes, what I expect is to skip existing files based on the filename returned by onBeforeSave.

**Comment by ibrod83** [comment]
did u try using the "fileName" attribute instead of onBeforeSave? (as you can see, too many options..)

**Comment by YuJian920** [comment]
If I use the fileName property, I can't dynamically change the file extension. But at least skipping files that already exist works, which is more important than customizing the extensions.
