### ISSUE TITLE
(node:1) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.

### ISSUE THREAD

**Issue by mayanksharma1202** [ibrod83/nodejs-file-downloader#69]
Hello

Now days this library is throwing warnings like (node:1) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.

I believe it is caused by underlined repo. can you please help in this matter?

**Comment by ibrod83** [comment]
I don't see this warning. Can you show your code? Are you sure it's caused by this package? Also, what node version are you running?

**Comment by mayanksharma1202** [comment]
My bad.. It was formData implementation who was giving this error.. I am using Node Alpine.
