### ISSUE TITLE
Add a way to see how many bytes are left to download

### ISSUE THREAD

**Issue by realshapes** [ibrod83/nodejs-file-downloader#7]
There should be a way to check how many bytes are left in a download, sort of like the way you get progress until it is complete. This would be a nice feature.

**Comment by ibrod83** [comment]
Yes, you're right. But, i think you can implement it yourself:
In the onProgress hook, get the first argument, which is the %. Then, access a property called fileSize on the downloader instance:
`onProgress: function (percentage) {
      const size = downloader.fileSize;//Assuming this is how you called your Download instance!
      const remainingFracture = (100 - percentage) / 100;
      const remainingSize = Math.round(remainingFracture * size);
      console.log('remainingSize',remainingSize)

    }`
Tell me if this worked for you. Please note, that this will NOT work, if the server doesn't supply a 'Content-Length' header!

**Comment by realshapes** [comment]
Ok, I will make a fork and try that. Maybe `onProgress` should be replaced altogether with this new function? I will open a pull with a readme update on how to track both the amount of bytes, and also how to convert that into a percentage using the current method

**Comment by realshapes** [comment]
Ok, I will try that solution. Thank you.

**Comment by realshapes** [comment]
I think it worked, but maybe add it to the package itself. I may fork and add that though.

**Comment by ibrod83** [comment]
no need to fork, i will do it soon :D

**Comment by realshapes** [comment]
> no need to fork, because to be honest, i don't know how to test locally the package, using the changes you commit. Your previous fork just involved documentation, so there was no need to test obviously. I will add this as an argument to onProgress later on.

You could probably just use the [npm link command](https://docs.npmjs.com/cli/v6/commands/npm-link).

**Comment by jacany** [comment]
> no need to fork, because to be honest, i don't know how to test locally the package, using the changes you commit. Your previous fork just involved documentation, so there was no need to test obviously. I will add this as an argument to onProgress later on.

I just realized what you were talking about. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally This should explain it.

**Comment by ibrod83** [comment]
Yes, i never collaborated with anyone on Github, but was always wondering how those guys actually review and test a pull request, before they decide if to accept it.

**Comment by jacany** [comment]
Also, im pretty sure it displays pull request branches in the github desktop app when you are switching a branch
