### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by y4nnick** [ibrod83/nodejs-file-downloader#8]
Hi!
Thanks for the great lib!

Do you plan on implement proxy support?
A way to configure a proxy for the filedownload would be amazing.

I could also give it a try and open a PR if wanted.

Best regards,
Yannnick

**Comment by ibrod83** [comment]
hey. That's a good idea, i will do it one day but can't say when.
If it's urgent for you, you can of course fork the lib and do it your self

**Comment by ibrod83** [comment]
I've added proxy support. This requires another dependency, so make sure to run npm install again.
