### ISSUE TITLE
How to get the downloaded file name?

### ISSUE THREAD

**Issue by QC-Development** [ibrod83/nodejs-file-downloader#9]
Can I get the "deduced" filename?

**Comment by ibrod83** [comment]
Ah lol, such a trivial feature, and i forgot to take care of it. I will change that in the upcoming days. For now, i don't see any workaround unfortunately. Thank you for pointing this out!

**Comment by ibrod83** [comment]
I've added an "onBeforeSave" hook. You can also override the name that was chosen.
